# https://www.tomray.dev/nestjs-docker-compose-postgres

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start -- -b swc
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
